"""AC1 — FastMCP schema assertion.

Parses the MCP schema generated by the FastMCP instance and asserts that
exactly six tools are present with the correct names.  No stores needed.
"""

from __future__ import annotations

import asyncio

EXPECTED_TOOLS = frozenset({"ask", "search", "search_graph", "get_policies", "query", "summarize"})


def test_schema_has_exactly_six_tools() -> None:
    """FastMCP generates exactly 6 tool entries from the @mcp.tool() decorators."""
    from graphrag.mcp._tools import mcp

    tools = asyncio.run(mcp.list_tools())
    names = {t.name for t in tools}
    assert names == EXPECTED_TOOLS, f"Expected {EXPECTED_TOOLS!r}, got {names!r}"


def test_schema_tool_names() -> None:
    """Each expected tool name is individually present in the generated schema."""
    from graphrag.mcp._tools import mcp

    tools = asyncio.run(mcp.list_tools())
    names = {t.name for t in tools}
    for expected in EXPECTED_TOOLS:
        assert expected in names, f"Tool {expected!r} missing from schema"


def test_ask_input_schema() -> None:
    """ask() input schema has a required 'question' string parameter."""
    from graphrag.mcp._tools import mcp

    tools = asyncio.run(mcp.list_tools())
    ask = next(t for t in tools if t.name == "ask")
    props = ask.inputSchema.get("properties", {})
    assert "question" in props, "'question' must be in ask inputSchema"
    assert props["question"].get("type") == "string"


def test_search_input_schema() -> None:
    """search() has 'question' (required), 'type' (optional), 'k' (optional, int)."""
    from graphrag.mcp._tools import mcp

    tools = asyncio.run(mcp.list_tools())
    search = next(t for t in tools if t.name == "search")
    props = search.inputSchema.get("properties", {})
    required = search.inputSchema.get("required", [])
    assert "question" in props
    assert "question" in required
    # type and k are optional
    assert "type" in props
    assert "k" in props
    assert "type" not in required
    assert "k" not in required


def test_get_policies_input_schema() -> None:
    """get_policies() has 'context' (required) and optional 'domain'."""
    from graphrag.mcp._tools import mcp

    tools = asyncio.run(mcp.list_tools())
    gp = next(t for t in tools if t.name == "get_policies")
    props = gp.inputSchema.get("properties", {})
    required = gp.inputSchema.get("required", [])
    assert "context" in props
    assert "context" in required
    assert "domain" in props
    assert "domain" not in required


def test_search_graph_input_schema() -> None:
    """search_graph() has 'uri' (required) and optional 'hops' (int default=1)."""
    from graphrag.mcp._tools import mcp

    tools = asyncio.run(mcp.list_tools())
    sg = next(t for t in tools if t.name == "search_graph")
    props = sg.inputSchema.get("properties", {})
    required = sg.inputSchema.get("required", [])
    assert "uri" in props
    assert "uri" in required
    assert "hops" in props
    assert "hops" not in required


def test_query_input_schema() -> None:
    """query() has 'template_name' (str) and 'params' (dict) both required."""
    from graphrag.mcp._tools import mcp

    tools = asyncio.run(mcp.list_tools())
    q = next(t for t in tools if t.name == "query")
    props = q.inputSchema.get("properties", {})
    required = q.inputSchema.get("required", [])
    assert "template_name" in props
    assert "params" in props
    assert "template_name" in required
    assert "params" in required


def test_summarize_input_schema() -> None:
    """summarize() has 'topic' (str, required)."""
    from graphrag.mcp._tools import mcp

    tools = asyncio.run(mcp.list_tools())
    s = next(t for t in tools if t.name == "summarize")
    props = s.inputSchema.get("properties", {})
    required = s.inputSchema.get("required", [])
    assert "topic" in props
    assert "topic" in required
